version: "3.5"

services:
  chefserver:
    container_name: chef-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CODE_VERSION: 18.04
        BASE_DISTRO: ubuntu
    ports:
      - 443:443
    networks:
      - mitlabs
    restart: always
networks:
  mitlabs:
    name: mitlabs
    driver: bridge